[package]
name = "inspirer-actix-ext-support"
version = "0.1.0"
authors = ["chongyi <xpz3847878@163.com>"]
edition = "2018"

[dependencies]
ahash = "0.7.0"
actix-web = "*"
log = "^0.4.0"
futures = "0.3.12"
anyhow = "^1.0.38"